### ISSUE TITLE
ktensor.full() not working as intended when replicating SVD functionality

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#167] opened 2023-06-30 19:01 UTC
The following example identifies a bug in the `ktensor.full()` computation:

```python
>>> import pyttb as ttb
>>> import numpy as np
>>> np.random.seed(0)
>>> A = np.random.rand(4,3)
>>> A
array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

>>> [U,S,V] = np.linalg.svd(A, full_matrices=False) # Compute the SVD.
>>> X = ttb.ktensor.from_data(S, [U, V]) # Store the SVD as a ktensor.
>>> X
ktensor of shape 4 x 3
weights=[2.21425506 0.29626672 0.21874633]
factor_matrices[0] =
[[-0.48665747 -0.08953811  0.54332309]
 [-0.41275168 -0.81483266  0.00407301]
 [-0.62010377  0.2250203  -0.73183668]
 [-0.45636813  0.52668447  0.41133746]]
factor_matrices[1] =
[[-0.42376582 -0.64907895 -0.63175869]
 [-0.65045995  0.70346017 -0.2864361 ]
 [ 0.63033672  0.28955189 -0.72030224]]
>>> print(f"U*S*V:\n{U@np.diag(S)@V}")
>>> print(f"\nX.factor_matrices[0]@np.diag(X.weights)@X.factor_matrices[1]:\n{X.factor_matrices[0]@np.diag(X.weights)@X.factor_matrices[1]}")
>>> print(f"\nX.full():\n{X.full()}") # Reassemble the original matrix.
U*S*V:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]

X.factor_matrices[0]@np.diag(X.weights)@X.factor_matrices[1]:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]

X.full():
tensor of shape 4 x 3
data[:, :] = 
[[ 0.39877691  0.64822137 -0.77252949]
 [ 0.54342533  0.42440376 -0.64663021]
 [ 0.63972383  0.98587716 -0.73088113]
 [ 0.27009548  0.74129398 -0.65659533]]
```

**Comment by ntjohnson1** [comment] 2023-08-27 15:33
This bug appears consistent with the MATLAB version:
```MATLAB
>> U = [-0.48665747  0.08953811  0.54332309;
       -0.41275168  0.81483266  0.00407301;
       -0.62010377 -0.2250203 -0.73183668;
       -0.45636813 -0.52668447  0.41133746];
>> S = [2.21425506 0.29626672 0.21874633];
>> V = [-0.42376582 -0.64907895 -0.63175869;
        0.65045995 -0.70346017  0.2864361;
        0.63033672  0.28955189 -0.72030224];
>> U*diag(S)*V

ans =

    0.5488    0.7152    0.6028
    0.5449    0.4237    0.6459
    0.4376    0.8918    0.9637
    0.3834    0.7917    0.5289
>> X = ktensor(transpose(S), {U,V})
X is a ktensor of size 4 x 3
	X.lambda = 
		    2.2143    0.2963    0.2187
	X.U{1} = 
		   -0.4867    0.0895    0.5433
		   -0.4128    0.8148    0.0041
		   -0.6201   -0.2250   -0.7318
		   -0.4564   -0.5267    0.4113
	X.U{2} = 
		   -0.4238   -0.6491   -0.6318
		    0.6505   -0.7035    0.2864
		    0.6303    0.2896   -0.7203
>> full(X, 1) % We implement version one but results are the same for 2
ans is a tensor of size 4 x 3
	ans(:,:) = 
	    0.3643   -0.6855   -0.7572
	    0.2300   -0.7640   -0.5068
	    0.7263   -0.8921   -0.7695
	    0.4727   -0.5218   -0.7470
```

**Comment by ntjohnson1** [comment] 2023-08-27 15:50
Ahh, I think this is just an interpretation issue. MATLAB `svd` returns U,S,V such that `X = U*S*V'` but numpy returns U,S,Vh such that `X=U*np.diag(S)*Vh`. So I think we just need to provide `Vh.transpose()` to the ktensor for things to be consistent

**Comment by ntjohnson1** [comment] 2023-08-27 15:56
Closing as not a bug with the following justification. Will make a note on the ktensor tutorial to fix there.

Minimal repro from above and [link ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html)to numpy svd doc
```python
>>> np.random.seed(0)
>>> A = np.random.rand(4,3)
>>> [U, S, Vh] = np.linalg.svd(A, full_matrices=False)
>>> X = ttb.ktensor([U, Vh.transpose()], S)
>>> X.full()
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]
>>> np.dot(U*S,Vh)
array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])
```

**Closed by ntjohnson1** 2023-08-27 15:56 UTC
Labels: bug
